### ISSUE TITLE
The newest uploaded iptyhon notebook file 1606 seems to be broken

### ISSUE THREAD

**Issue by whimian** [seg/tutorials#31]
When I download the file and try to open it with jupyter notebook, an error showed up:

```
"Error loading notebook
Unreadable Notebook: C:\span\Python\seg_tutorial\tle_16_04\Wavelet_estimation_for_well_ties.ipynb NotJSONError('Notebook does not appear to be JSON: u\'\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang="e...',)"
```

And I'm using Anaconda on windows.

**Comment by kwinkunks** [comment]
It looks like you're trying to open the HTML version of the notebook. You need the `.ipynb` version of the file. You can get this by cloning the repo (or a fork of it), or by clicking the **Raw** button in GitHub and saving that file. It's best to clone everything, because then you get the data too.

See https://help.github.com/articles/cloning-a-repository/

**Comment by whimian** [comment]
Thank you. I'll consider cloning the repo.
